<?php

namespace ApiBundle\Repository;

/**
 * FablabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FablabRepository extends \Doctrine\ORM\EntityRepository
{
}
