<?php

namespace ApiBundle\Repository;

/**
 * MakerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MakerRepository extends \Doctrine\ORM\EntityRepository
{
}
