<?php

namespace ApiBundle\Repository;

/**
 * MotivationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotivationRepository extends \Doctrine\ORM\EntityRepository
{
}
