<?php

namespace ApiBundle\Repository;

/**
 * PersonnalityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonnalityRepository extends \Doctrine\ORM\EntityRepository
{
}
