<?php

namespace ApiBundle\Repository;

/**
 * SkillDomainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillDomainRepository extends \Doctrine\ORM\EntityRepository
{
}
