<?php

namespace ApiBundle\Repository;

/**
 * SubsidiaryProfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubsidiaryProfilRepository extends \Doctrine\ORM\EntityRepository
{
}
