<?php

namespace ApiBundle\Repository;

/**
 * URLRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class URLRepository extends \Doctrine\ORM\EntityRepository
{
}
