<?php

namespace ApiBundle\Repository;

/**
 * UsersFablabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersFablabRepository extends \Doctrine\ORM\EntityRepository
{
}
