<?php

namespace ApiBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAllMakers()
	{
		$query = $this->getEntityManager()->createQueryBuilder('ca1')
	        ->add('select', 'user')
	        ->add('from', 'ApiBundle:User user')
	        ->join('user.usersFablabs', 'usersFablabs', 'WITH', "usersFablabs.role='maker'")
	        ->getQuery();

    	return $query->getResult();
	}

	public function connect($login, $password)
	{
		$count = $this->getEntityManager()->createQueryBuilder()
		->select('count(user)')
		->add('from','ApiBundle:User user')
        ->where('user.login LIKE :login')
        ->setParameter('login', '%'.$login.'%')
        ->andWhere('user.password LIKE :password')
        ->setParameter('password', '%'.$password.'%')
		->getQuery()
		->getSingleScalarResult();

		return intval($count) == 1;
	}
}
