<?php

namespace ApiBundle\Repository;

/**
 * WebsiteAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteAccountRepository extends \Doctrine\ORM\EntityRepository
{
}
